ARG BUILD_VERSION=0.1.0
ARG BUILD_ARCH=amd64

FROM pymcdev/pymc-repeater:dev

ARG BUILD_VERSION
ARG BUILD_ARCH

COPY run.sh /run.sh
COPY pymc-repeater.example.yaml /usr/share/pymc-repeater/config.yaml.example

RUN chmod a+x /run.sh

LABEL \
  io.hass.version="${BUILD_VERSION}" \
  io.hass.type="app" \
  io.hass.arch="${BUILD_ARCH}" \
  org.opencontainers.image.title="Home Assistant Add-on: pyMC Repeater" \
  org.opencontainers.image.description="Home Assistant wrapper for pyMC Repeater" \
  org.opencontainers.image.source="https://github.com/pyMC-dev/pyMC_Repeater"

ENTRYPOINT ["/run.sh"]
